### ISSUE TITLE
Add inline syntax to Vili

### ISSUE THREAD

**Issue by Sygmei** [Sygmei/ViliData#7]
```yaml
A:
  B:
    c:"Hello"
  D:
    e:3.14
F:
  g:666
  H:[1,2,3,4]
```
could be inlined to

```yaml
A:{B:{c:"Hello"},D:{e:3.14}},F:{g:666,H:[1,2,3,4]}
```
